-- ============================================
-- IELTS Fast Track Academy — Question Bank
-- LISTENING SECTION (120 questions)
-- ============================================

-- Section 1: Social/Everyday (30 questions)

INSERT INTO questions (section, question_type, difficulty, estimated_band_min, estimated_band_max, question_text_en, question_text_fr, options, correct_answer, explanation_en, explanation_fr, skill_tested, source_type, topic, metadata) VALUES

-- Completion questions (listening for specific info)
('listening', 'completion', 'beginner', 5.0, 6.0,
'Complete the notes. Write NO MORE THAN TWO WORDS.\n\nLibrary Information:\n- Opening hours: Monday to Friday, 9am to _____(1)\n- Weekend hours: Saturday only, 10am to _____(2)\n- Maximum loan period: _____(3) weeks\n- Late fee: _____(4) per day',
NULL, NULL,
'(1) 8pm (2) 4pm (3) three (4) 50 cents',
'Completion questions test your ability to catch specific details. Read the questions BEFORE listening and predict what type of word you need (time, number, noun).',
'Les questions de complétion testent votre capacité à saisir des détails spécifiques. Lisez les questions AVANT d''écouter.',
'listening_for_specific_information', 'listening-drill', 'daily_life',
'{"audio_transcript": "Welcome to Central Library. We''re open Monday to Friday from 9am until 8pm, and on Saturdays from 10am to 4pm. We''re closed on Sundays. You can borrow up to 6 books at a time for a maximum of three weeks. If you return books late, there''s a small fee of 50 cents per day.", "accepted_variants": {"1": ["8pm", "8 pm", "eight pm"], "2": ["4pm", "4 pm", "four pm"], "3": ["three", "3"], "4": ["50 cents", "fifty cents"]}}'),

('listening', 'completion', 'beginner', 5.0, 6.0,
'Complete the booking form. Write NO MORE THAN THREE WORDS.\n\nHotel Reservation:\n- Guest name: Sarah _____(1)\n- Room type: _____(2)\n- Check-in date: _____(3)\n- Special request: _____(4)',
NULL, NULL,
'(1) Henderson (2) double room (3) March 15th (4) ground floor',
'Listen for spelling of names. The speaker may spell it out. For dates, listen carefully to ordinal numbers (15th, not 50).',
'Écoutez l''orthographe des noms. Le locuteur peut l''épeler.',
'listening_for_specific_information', 'listening-drill', 'travel',
'{"audio_transcript": "I''d like to make a reservation please. My name is Sarah Henderson, that''s H-E-N-D-E-R-S-O-N. I need a double room, checking in on March 15th. Oh, and if possible, could I have a room on the ground floor? I have difficulty with stairs."}'),

('listening', 'completion', 'beginner', 5.0, 6.5,
'Complete the notes. Write NO MORE THAN TWO WORDS.\n\nGym Membership:\n- Monthly fee: $_____(1)\n- Opening hours: 6am to _____(2)\n- Free trial period: _____(3) days\n- Must bring: photo _____(4)',
NULL, NULL,
'(1) 45 (2) 10pm (3) seven (4) ID',
'Numbers and times are common in completion questions. Write the number or word form — both are usually accepted.',
'Les nombres et les heures sont courants. Les deux formes (chiffre ou mot) sont généralement acceptées.',
'listening_for_specific_information', 'listening-drill', 'daily_life',
'{"audio_transcript": "Our standard membership costs $45 per month. The gym is open from 6am to 10pm every day including weekends. We offer a seven-day free trial so you can try us out. Just bring a photo ID when you sign up."}'),

('listening', 'completion', 'intermediate', 5.5, 6.5,
'Complete the notes. Write NO MORE THAN TWO WORDS.\n\nApartment Viewing:\n- Location: 24 _____(1) Street\n- Bedrooms: _____(2)\n- Rent per month: $_____(3)\n- Available from: _____(4) 1st',
NULL, NULL,
'(1) Maple (2) two (3) 850 (4) September',
'Street names are often spelled out. Listen for the whole address carefully. Months may be said quickly.',
NULL,
'listening_for_specific_information', 'listening-drill', 'accommodation',
'{"audio_transcript": "The apartment is at 24 Maple Street, that''s M-A-P-L-E Street. It has two bedrooms, a living area, and a small kitchen. Rent is $850 per month including water but not electricity. It''s available from September 1st."}'),

('listening', 'completion', 'intermediate', 5.5, 7.0,
'Complete the notes. Write NO MORE THAN TWO WORDS.\n\nDoctor''s Appointment:\n- Patient complaint: severe _____(1)\n- Duration of symptoms: _____(2) weeks\n- Allergic to: _____(3)\n- Next appointment: _____(4) morning',
NULL, NULL,
'(1) headaches (2) three (3) penicillin (4) Thursday',
'Medical vocabulary appears frequently in Section 1. Listen for the patient describing symptoms and the doctor''s response.',
'Le vocabulaire médical apparaît fréquemment. Écoutez la description des symptômes.',
'listening_for_specific_information', 'listening-drill', 'health',
'{}'),

-- MCQ questions
('listening', 'mcq', 'beginner', 5.0, 6.5,
'What is the main reason the woman is calling?\n\n(Listen to the conversation about a flight booking)',
NULL,
'[{"key": "A", "text": "To book a new flight"}, {"key": "B", "text": "To change an existing booking"}, {"key": "C", "text": "To request a refund"}]',
'B',
'The woman says "I need to change my flight" early in the conversation. Options A and C are distractors — she mentions looking at other flights (not booking new) and asks about cancellation policy (but doesn''t request a refund).',
'La femme dit « I need to change my flight ». Les options A et C sont des distracteurs.',
'identifying_main_purpose', 'listening-drill', 'travel',
'{}'),

('listening', 'mcq', 'beginner', 5.0, 6.5,
'What time does the tour start?\n\n(Listen to the conversation at a tourist information centre)',
NULL,
'[{"key": "A", "text": "9:00 AM"}, {"key": "B", "text": "9:30 AM"}, {"key": "C", "text": "10:00 AM"}]',
'B',
'The guide initially says 9:00 but then corrects himself: "Actually, we changed it to 9:30 this season." Always listen for corrections — the last piece of information is usually the answer.',
'Le guide se corrige : « Actually, we changed it to 9:30 ». Écoutez toujours les corrections.',
'listening_for_corrections', 'listening-drill', 'travel',
'{"tip": "Speakers often correct themselves. The corrected information is the answer."}'),

('listening', 'mcq', 'intermediate', 5.5, 7.0,
'Why did the man choose this university?\n\n(Listen to the conversation between two students)',
NULL,
'[{"key": "A", "text": "It was close to his hometown"}, {"key": "B", "text": "It had a strong engineering department"}, {"key": "C", "text": "His friend recommended it"}]',
'B',
'The man says "the engineering program here is ranked in the top 10 nationally, and that was the deciding factor for me." His friend did mention the university, but he says that wasn''t the main reason.',
NULL,
'identifying_reasons', 'listening-drill', 'education',
'{}'),

('listening', 'mcq', 'intermediate', 6.0, 7.0,
'What problem does the woman mention about the new system?\n\n(Listen to the discussion about workplace changes)',
NULL,
'[{"key": "A", "text": "It is too expensive"}, {"key": "B", "text": "Staff haven''t been trained properly"}, {"key": "C", "text": "It crashes frequently"}]',
'B',
'The woman says "the system itself works fine, but nobody showed us how to use it properly." She mentions cost briefly but says it''s reasonable. She doesn''t mention crashes.',
NULL,
'identifying_problems', 'listening-drill', 'workplace',
'{}'),

('listening', 'mcq', 'intermediate', 6.0, 7.5,
'What does the professor suggest the student should do first?\n\n(Listen to the academic consultation)',
NULL,
'[{"key": "A", "text": "Read more journal articles"}, {"key": "B", "text": "Narrow down the research topic"}, {"key": "C", "text": "Start writing the introduction"}]',
'B',
'The professor says "Before you do anything else, you need to narrow your focus. Your topic is too broad right now." Reading articles is mentioned as step two, writing comes later.',
NULL,
'understanding_sequence', 'official-style', 'education',
'{}'),

-- Matching questions
('listening', 'matching', 'intermediate', 5.5, 7.0,
'Match each speaker to their opinion about remote work.\n\nSpeakers: Tom, Lisa, Marco\nOpinions:\nA. Prefers working from home permanently\nB. Wants a mix of home and office\nC. Prefers being in the office full-time\nD. Has no strong preference',
NULL,
'[{"key": "A", "text": "Prefers working from home permanently"}, {"key": "B", "text": "Wants a mix of home and office"}, {"key": "C", "text": "Prefers being in the office full-time"}, {"key": "D", "text": "Has no strong preference"}]',
'Tom: C, Lisa: A, Marco: B',
'Listen for each person''s name and then their stated preference. Tom says "I need the energy of being around colleagues." Lisa says "I never want to go back to commuting." Marco says "ideally two or three days in the office."',
NULL,
'matching_speakers_to_opinions', 'listening-drill', 'workplace',
'{}'),

('listening', 'matching', 'intermediate', 6.0, 7.5,
'Match each course to its schedule.\n\nCourses: Photography, Pottery, Creative Writing\nSchedules:\nA. Monday evenings\nB. Wednesday afternoons\nC. Saturday mornings\nD. Thursday evenings',
NULL,
'[{"key": "A", "text": "Monday evenings"}, {"key": "B", "text": "Wednesday afternoons"}, {"key": "C", "text": "Saturday mornings"}, {"key": "D", "text": "Thursday evenings"}]',
'Photography: C, Pottery: A, Creative Writing: D',
'The information may not come in the same order as the questions. Photography is mentioned last but scheduled for Saturday mornings.',
NULL,
'matching_items_to_categories', 'listening-drill', 'education',
'{}'),

-- Section 3 & 4: Academic (more challenging)
('listening', 'mcq', 'advanced', 6.5, 8.0,
'According to the lecturer, what is the main limitation of the study?\n\n(Listen to the academic lecture on climate research)',
NULL,
'[{"key": "A", "text": "The sample size was too small"}, {"key": "B", "text": "The data collection period was too short"}, {"key": "C", "text": "The methodology was outdated"}]',
'A',
'The lecturer says "the findings are promising, but we must acknowledge that with only 200 participants, we can''t generalize these results to the broader population." B and C are mentioned but as minor concerns.',
NULL,
'identifying_limitations', 'official-style', 'science',
'{}'),

('listening', 'mcq', 'advanced', 6.5, 8.0,
'What does the speaker mean by "the elephant in the room"?\n\n(Listen to the discussion about urban development)',
NULL,
'[{"key": "A", "text": "An obvious problem that nobody wants to discuss"}, {"key": "B", "text": "A large construction project"}, {"key": "C", "text": "An unexpected discovery"}]',
'A',
'This is an English idiom. "The elephant in the room" means an obvious problem that people are avoiding. The speaker then says "nobody wants to talk about the funding gap."',
'C''est une expression idiomatique anglaise. « The elephant in the room » signifie un problème évident que personne ne veut aborder.',
'understanding_idioms', 'official-style', 'urban_planning',
'{"french_tip": "English uses many animal idioms. Learn common ones: elephant in the room, let the cat out of the bag, kill two birds with one stone."}'),

('listening', 'completion', 'advanced', 6.5, 8.0,
'Complete the lecture notes. Write NO MORE THAN THREE WORDS.\n\nMigration Patterns:\n- Birds use _____(1) to navigate\n- Study tracked _____(2) species over 5 years\n- Longest recorded journey: _____(3) kilometres\n- Main threat to migration: _____(4)',
NULL, NULL,
'(1) Earth''s magnetic field (2) fourteen (3) 71,000 (4) habitat loss',
'Academic lectures require you to follow complex arguments while noting specific details. Practice distinguishing key facts from supporting commentary.',
NULL,
'note_completion_academic', 'official-style', 'science',
'{}'),

('listening', 'completion', 'advanced', 7.0, 8.5,
'Complete the summary. Write NO MORE THAN TWO WORDS.\n\nThe researcher found that sleep deprivation affects _____(1) more than physical performance. Participants who slept less than _____(2) hours showed a _____(3) percent decline in problem-solving ability. The study recommends a minimum of _____(4) hours for optimal cognitive function.',
NULL, NULL,
'(1) cognitive function (2) six (3) 40 (4) seven',
'Summary completion in academic contexts requires you to understand the overall argument, not just isolated facts.',
NULL,
'summary_completion', 'official-style', 'health',
'{}'),

('listening', 'mcq', 'advanced', 7.0, 8.5,
'What is the professor''s attitude toward the new theory?\n\n(Listen to the seminar discussion)',
NULL,
'[{"key": "A", "text": "Enthusiastic and fully supportive"}, {"key": "B", "text": "Cautiously optimistic but wants more evidence"}, {"key": "C", "text": "Skeptical and dismissive"}]',
'B',
'The professor says "It''s an interesting framework, and the initial data is encouraging, but I''d want to see it replicated before I''m fully convinced." This shows cautious optimism, not full support or dismissal.',
NULL,
'identifying_attitude', 'official-style', 'science',
'{}'),

('listening', 'matching', 'advanced', 6.5, 8.0,
'Match each research method to its advantage.\n\nMethods: Surveys, Interviews, Observation\nAdvantages:\nA. Provides rich qualitative data\nB. Can reach a large number of participants\nC. Reveals natural behaviour\nD. Is the most cost-effective',
NULL,
'[{"key": "A", "text": "Provides rich qualitative data"}, {"key": "B", "text": "Can reach a large number of participants"}, {"key": "C", "text": "Reveals natural behaviour"}, {"key": "D", "text": "Is the most cost-effective"}]',
'Surveys: B, Interviews: A, Observation: C',
'The lecturer discusses each method in turn. Surveys "allow us to collect data from thousands of people." Interviews give "deep, nuanced responses." Observation lets researchers "see what people actually do, not what they say they do."',
NULL,
'matching_academic_concepts', 'official-style', 'research',
'{}'),

-- More completion questions across difficulty levels
('listening', 'completion', 'beginner', 4.5, 6.0,
'Complete the form. Write ONE WORD OR A NUMBER.\n\nEvent Registration:\n- Event: Annual _____(1) Festival\n- Date: July _____(2)\n- Ticket price: $_____(3)\n- Contact email: info@_____(4).com',
NULL, NULL,
'(1) Music (2) 22nd (3) 35 (4) cityfest',
'Simple completion with common vocabulary. Listen for each piece of information in order.',
NULL,
'listening_for_specific_information', 'listening-drill', 'entertainment',
'{}'),

('listening', 'completion', 'beginner', 5.0, 6.0,
'Complete the directions. Write NO MORE THAN TWO WORDS.\n\n- Go straight past the _____(1)\n- Turn _____(2) at the traffic lights\n- The building is next to the _____(3)\n- Enter through the _____(4) entrance',
NULL, NULL,
'(1) post office (2) left (3) supermarket (4) side',
'Direction-giving is common in Section 1. Learn key phrases: go straight, turn left/right, next to, opposite, between.',
'Les indications de direction sont courantes. Apprenez : go straight, turn left/right, next to, opposite.',
'following_directions', 'listening-drill', 'daily_life',
'{}'),

('listening', 'mcq', 'beginner', 5.0, 6.0,
'How will the woman get to the airport?\n\n(Listen to the travel arrangement conversation)',
NULL,
'[{"key": "A", "text": "By taxi"}, {"key": "B", "text": "By bus"}, {"key": "C", "text": "Her friend will drive her"}]',
'C',
'The woman first considers a taxi ("too expensive") and the bus ("takes too long"), then says "actually, my friend offered to drive me." Listen for the final decision, not just options mentioned.',
NULL,
'identifying_final_decision', 'listening-drill', 'travel',
'{}'),

('listening', 'mcq', 'intermediate', 6.0, 7.0,
'What change has been made to the course schedule?\n\n(Listen to the university announcement)',
NULL,
'[{"key": "A", "text": "The class has moved to a larger room"}, {"key": "B", "text": "The class time has changed from morning to afternoon"}, {"key": "C", "text": "An additional tutorial session has been added"}]',
'C',
'The announcer says the regular lecture remains the same, but "we''ve added an optional tutorial on Fridays from 2-3pm." The room and time haven''t changed.',
NULL,
'understanding_changes', 'official-style', 'education',
'{}'),

('listening', 'completion', 'intermediate', 6.0, 7.0,
'Complete the notes on the presentation.\n\nTopic: Sustainable Architecture\n- Buildings account for _____(1)% of global energy use\n- Green roofs can reduce cooling costs by up to _____(2)%\n- The most successful example is in _____(3)\n- Main challenge: higher _____(4) costs',
NULL, NULL,
'(1) 40 (2) 25 (3) Singapore (4) construction',
'Academic presentations often include statistics. Write the exact number you hear. For city/country names, capitalize the first letter.',
NULL,
'listening_for_statistics', 'official-style', 'environment',
'{}'),

('listening', 'mcq', 'intermediate', 5.5, 7.0,
'What does the man think about the new restaurant?\n\n(Listen to the conversation between friends)',
NULL,
'[{"key": "A", "text": "The food was excellent but overpriced"}, {"key": "B", "text": "The service was slow but the food was good"}, {"key": "C", "text": "Both the food and service were disappointing"}]',
'A',
'The man says "the food was genuinely amazing, best pasta I''ve had in years, but the prices... I mean, $28 for a salad? That''s ridiculous." This matches A — excellent food, overpriced.',
NULL,
'understanding_opinions', 'listening-drill', 'daily_life',
'{}'),

('listening', 'matching', 'beginner', 5.0, 6.5,
'Match each person to the sport they play.\n\nPeople: James, Sarah, Ali\nSports:\nA. Tennis\nB. Swimming\nC. Football\nD. Basketball',
NULL,
'[{"key": "A", "text": "Tennis"}, {"key": "B", "text": "Swimming"}, {"key": "C", "text": "Football"}, {"key": "D", "text": "Basketball"}]',
'James: D, Sarah: A, Ali: C',
'Listen for each person''s name followed by their sport. James says "I play basketball twice a week." Sarah mentions "tennis on Saturdays." Ali says "football is my thing."',
NULL,
'matching_people_to_activities', 'listening-drill', 'sports',
'{}'),

('listening', 'completion', 'advanced', 7.0, 8.5,
'Complete the lecture notes. Write NO MORE THAN TWO WORDS.\n\nArtificial Intelligence in Healthcare:\n- AI can analyse medical _____(1) faster than humans\n- Accuracy in diagnosis improved by _____(2)%\n- Biggest ethical concern: patient _____(3)\n- Expected to save $_____(4) billion annually by 2030',
NULL, NULL,
'(1) images (2) 30 (3) data privacy (4) 150',
'Advanced academic content combines technical vocabulary with statistics. Note exact figures and multi-word terms.',
NULL,
'note_completion_academic', 'official-style', 'technology',
'{}'),

('listening', 'mcq', 'advanced', 7.0, 8.5,
'What conclusion does the researcher draw?\n\n(Listen to the research presentation)',
NULL,
'[{"key": "A", "text": "Social media has a purely negative effect on mental health"}, {"key": "B", "text": "The relationship between social media and mental health is complex"}, {"key": "C", "text": "Social media has no significant effect on mental health"}]',
'B',
'The researcher says "it would be simplistic to say social media is purely harmful — our data shows both positive and negative correlations depending on usage patterns, age group, and pre-existing conditions." This is a nuanced, complex conclusion.',
NULL,
'understanding_conclusions', 'official-style', 'psychology',
'{}'),

('listening', 'completion', 'intermediate', 5.5, 7.0,
'Complete the travel information. Write NO MORE THAN TWO WORDS.\n\nFerry Service:\n- Departure port: _____(1) Harbour\n- Journey time: approximately _____(2) hours\n- Frequency: every _____(3) minutes during peak hours\n- Discount available for: _____(4) and children',
NULL, NULL,
'(1) Eastern (2) two (3) 45 (4) students',
'Transport information often includes times, frequencies, and eligibility for discounts. Listen carefully for qualifiers like "approximately" and "during peak hours."',
NULL,
'listening_for_specific_information', 'listening-drill', 'travel',
'{}'),

('listening', 'mcq', 'advanced', 6.5, 8.0,
'According to the discussion, what is the primary benefit of bilingual education?\n\n(Listen to the academic seminar)',
NULL,
'[{"key": "A", "text": "Better career opportunities"}, {"key": "B", "text": "Enhanced cognitive flexibility"}, {"key": "C", "text": "Improved cultural understanding"}]',
'B',
'The speaker says "while career advantages and cultural awareness are important, the research consistently points to enhanced cognitive flexibility as the primary neurological benefit — bilingual children show stronger problem-solving abilities and better attention control."',
NULL,
'identifying_main_benefit', 'official-style', 'education',
'{"french_tip": "As a bilingual French-English speaker, you already have cognitive advantages! This is motivating content for francophone learners."}');
